//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SOAP.numberConverter {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NumberConversionSoapBinding", Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberConversion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NumberToWordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback NumberToDollarsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NumberConversion() {
            this.Url = global::SOAP.Properties.Settings.Default.SOAP_numberConverter_NumberConversion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NumberToWordsCompletedEventHandler NumberToWordsCompleted;
        
        /// <remarks/>
        public event NumberToDollarsCompletedEventHandler NumberToDollarsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.dataaccess.com/webservicesserver/", ResponseNamespace="http://www.dataaccess.com/webservicesserver/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NumberToWords(ulong ubiNum) {
            object[] results = this.Invoke("NumberToWords", new object[] {
                        ubiNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NumberToWordsAsync(ulong ubiNum) {
            this.NumberToWordsAsync(ubiNum, null);
        }
        
        /// <remarks/>
        public void NumberToWordsAsync(ulong ubiNum, object userState) {
            if ((this.NumberToWordsOperationCompleted == null)) {
                this.NumberToWordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNumberToWordsOperationCompleted);
            }
            this.InvokeAsync("NumberToWords", new object[] {
                        ubiNum}, this.NumberToWordsOperationCompleted, userState);
        }
        
        private void OnNumberToWordsOperationCompleted(object arg) {
            if ((this.NumberToWordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NumberToWordsCompleted(this, new NumberToWordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.dataaccess.com/webservicesserver/", ResponseNamespace="http://www.dataaccess.com/webservicesserver/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NumberToDollars(decimal dNum) {
            object[] results = this.Invoke("NumberToDollars", new object[] {
                        dNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NumberToDollarsAsync(decimal dNum) {
            this.NumberToDollarsAsync(dNum, null);
        }
        
        /// <remarks/>
        public void NumberToDollarsAsync(decimal dNum, object userState) {
            if ((this.NumberToDollarsOperationCompleted == null)) {
                this.NumberToDollarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNumberToDollarsOperationCompleted);
            }
            this.InvokeAsync("NumberToDollars", new object[] {
                        dNum}, this.NumberToDollarsOperationCompleted, userState);
        }
        
        private void OnNumberToDollarsOperationCompleted(object arg) {
            if ((this.NumberToDollarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NumberToDollarsCompleted(this, new NumberToDollarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void NumberToWordsCompletedEventHandler(object sender, NumberToWordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NumberToWordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NumberToWordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void NumberToDollarsCompletedEventHandler(object sender, NumberToDollarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NumberToDollarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NumberToDollarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591